# 生产环境
server:
  port: 1234

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql:///db_tmos?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
  output:
    ansi:
      enabled: always